# Generated by Django 3.2.7 on 2021-09-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=8)),
                ('NAME', models.CharField(max_length=50)),
                ('CLASS', models.CharField(max_length=10)),
                ('FACULTY', models.CharField(max_length=30)),
                ('AGE', models.IntegerField()),
            ],
        ),
    ]
