CREATE DATABASE WEB_TUTO;
USE WEB_TUTO

CREATE TABLE STUDENT_INFO(
	ID INT NOT NULL,
	NAME NVARCHAR(50) NOT NULL,
	CLASS NVARCHAR(10) NOT NULL,
	FACULTY NVARCHAR(30)NOT NULL,
	AGE INT NOT NULL
)

ALTER TABLE STUDENT_INFO ALTER COLUMN ID CHAR(8);

INSERT INTO STUDENT_INFO (ID, NAME, CLASS, FACULTY, AGE)
VALUES('19521943', 'THANH NHAN', 'KHCL2019.2', 'KHOA HOC MAY TINH', 19);

INSERT INTO STUDENT_INFO (ID, NAME, CLASS, FACULTY, AGE)
VALUES('19521899', 'THÀNH NGHĨA', 'KHCL2019.2', 'KHOA HOC MAY TINH', 19);

SELECT * FROM STUDENT_INFO